squashapp: Test cleanup and improvements
We now log the failed tests at the end of the test run.

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -1,7 +1,7 @@
 #!/bin/bash
-set -e
+set -e -u
 
-cd "$(dirname "$0")"
+cd "$(dirname "${BASH_SOURCE[0]}")"
 
 source lib.sh
 
@@ -10,7 +10,8 @@ for TESTFILE in *.test; do
     . "${TESTFILE}"
 done
 
-log '\n%d tests failed' "${#FAILED[@]}"
+log
+log "${#FAILED[@]} tests failed"
 for failed in "${FAILED[@]}"; do
-    log '- %s' "${failed}"
+    log "- ${failed}"
 done
